src/components/Navigation.jsx
src/pages/telegram.mdx

Adding telegram provider page and some examples that how to implement it

feat: :rocket: add telegram provider page

---

src/components/Navigation.jsx
src/pages/agentsOpenAi.mdx
src/pages/shopify.mdx

agents open ai page
- documentation and use case

feat: :memo: Adding agents openai page

---

package-lock.json
src/components/Navigation.jsx
src/pages/queueLimit.mdx

-Adding to the documentation how to implement and manage the queue limit for high concurrencies on the chatbot

FEAT: adding Queue limit page ✨

---

src/components/Resources.jsx
src/pages/events.mdx
src/pages/pratices.mdx
src/pages/queueLimit.mdx

Just some typing corrections 🚀

Tyiping corrections

---

src/pages/add-functions.mdx

With this pr:
We will have the documentation according to the spanish version addFunctions docs
Without this pr: 
We will present a generic message

ADD: addFunctions docs

---

README.md
src/pages/_app.jsx
src/pages/add-functions.mdx
src/pages/agentsOpenAi.mdx
src/pages/context.mdx
src/pages/databases.mdx
src/pages/methods.mdx
src/pages/providers.mdx
src/pages/queueLimit.mdx
src/pages/quickstart.mdx

fix undefined title into pageProps and add section that exposes how to export title and description into pages

feat: :memo: Fix undefined title into pageprops

---

src/pages/shopify.mdx

add new sections and corrections into shopify page

Shopify page

---

src/pages/agentsOpenAi.mdx
src/pages/shopify.mdx
src/pages/telegram.mdx

add new sections into telegram page with some screens and examples

Telegram page

---

src/components/Navigation.jsx
src/pages/plugins-contributing.mdx

add the steps to create a new package or contributing into existing one onto bot-plugins mono repo

Contributing | bot-plugins

---

src/pages/shopify.mdx

add link to test into shopify page

link to test shopify

---

src/pages/shopify.mdx

update shopify page relationship with bot-plugin package

feat: :memo: update shopify page

---

src/components/Header.jsx
src/components/LanguajeSelector.jsx
src/components/Logo.jsx
src/components/Navigation.jsx
src/pages/pt/add-functions.mdx
src/pages/pt/methods.mdx

now is possible push an entire route into current language and add toggle language is avaliable
other fixing added too

Dynamic routing language

---

src/pages/en/providers/twilio.mdx

This commit includes the migration of documentation content from Spanish to English from the [previous documentation](https://bot-whatsapp.netlify.app/docs/providers/twilio/).
The translated content now accurately reflects the information about Twilio as a builderbot provider.
Video showing the updated content: https://www.loom.com/share/7bc0cc1f0e4e4247add94a60bbe0f896?sid=c3be8348-d593-4b54-9964-e9a93dab7f3c

feat(providers): update twilio content

---

src/pages/en/add-functions/index.mdx
src/pages/es/add-functions/index.mdx
src/pages/pt/add-functions/index.mdx

In several examples, the definition of `flowDynamic` is being written as `fowDynamic`.

fix(typo): correct flow dynamic definition

---

src/components/Navigation.jsx
src/pages/en/showcases/gotoflow-use.mdx
src/pages/es/showcases/gotoflow-use.mdx
src/pages/pt/showcases/gotoflow-use.mdx

Add GotoFlow flow for conversation transitions in WhatsApp bot

docs: :zap: GotoFlow use case added

---

services/get-profiles.js

feat: :zap: add perf cache

---

src/pages/en/databases/index.mdx

feat: :memo: add provider firebase

---

src/components/Navigation.jsx
src/pages/en/tutorials/chatbot-with-context.mdx
src/pages/en/tutorials/chatbot-with-vision.mdx

feat: :memo: add new section tutorials

---

src/components/Navigation.jsx
src/pages/en/plugins/langchain.mdx
src/pages/en/tutorials/langchain.mdx
src/pages/en/tutorials/tricks-meta.mdx

feat: :memo: add new tuto meta tricks

---

src/pages/en/databases/index.mdx
src/pages/en/databases/postgres/uses-cases/index.mdx
src/pages/en/databases/postgres/uses-cases/uses-cases-supabase.mdx

feat: :memo: add use case database postgres connection to supabase

---

src/pages/en/methods/index.mdx

Typo in Update index.mdx

---

src/components/Navigation.jsx
src/pages/en/showcases/multiple-messages.mdx

Helloo Leifer, im a fan 
Here is my contribution to the bot documentation with my showcase of multiple messages
Sorry for the delay

Create multiple messages showcase and add to navigation menu
